import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import Head from 'next/head'
import { useContext, useEffect } from 'react'
import { EventContext } from '@/contexts/EventContext'
import {
  DefaultLayout,
  Divider,
  Heading,
  Loading,
  DynamicComponent
} from '@/components'
import { AppContext } from '@/contexts/AppContext'

const Home: NextPage = () => {
  const { handleEvent } = useContext(EventContext)
  const { loading, setLoading } = useContext(AppContext)

  const router = useRouter()
  const { id, token } = router.query

  useEffect(() => {
    setLoading(true)
    fetch('/api/event/' + id + '/' + token)
      .then((res) => res.json())
      .then((result) => {
        handleEvent(result.data)
        setLoading(false)
      })
      .catch((err) => console.log(err))
  }, [id, token])

  return (
    <>
      <Head>
        <title>Next Integra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Heading />
        <Divider />
        {loading ? <Loading /> : <DynamicComponent />}
      </DefaultLayout>
    </>
  )
}

export default Home

// https://942tlq.sse.codesandbox.io/1554292?token=4b1110c1b17719f41b310ac99a33daa2b6493053ed2a359515caf85ed6ad3976
