import type { NextPage } from 'next'
import Head from 'next/head'
import { DefaultLayout, Heading } from '@/components'
import { useContext, useEffect } from 'react'
import { AppContext } from '@/contexts/AppContext'

const Home: NextPage = () => {
  const { content, setContent } = useContext(AppContext)

  const description =
    'Ops... Nao ha parametros para continuar!\nCaso precise de ajuda por gentileza entre em contato conosco pelo numero (43)3348-1234'

  useEffect(() => {
    setContent({
      ...content,
      body: {
        description
      }
    })
  })

  return (
    <>
      <Head>
        <title>Next Integra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen h-screen relative font-sans overflow-hidden">
        <DefaultLayout>
          <Heading />
          <h3 className="text-xl">Ops... Nao ha parametros para continuar!</h3>
          <h3 className="text-xl">
            Caso precise de ajuda por gentileza entre em contato conosco pelo
            numero (43)3348-1234
          </h3>
        </DefaultLayout>
      </div>
    </>
  )
}

export default Home

// https://942tlq.sse.codesandbox.io/1554292?token=4b1110c1b17719f41b310ac99a33daa2b6493053ed2a359515caf85ed6ad3976
